export const PERK_ICON_NAMES = [
  "steady-hand",
  "bigger-targets",
  "balanced",
  "alert-triangle",
  "target",
  "crack",
  "hourglass",
  "eye",
  "clock",
  "trending-up",
  "flame",
  "dice",
  "star",
  "gem",
  "coins",
  "stairs",
  "coin",
  "burst",
  "sunrise",
  "shield",
  "heart",
  "heart-plus",
  "wheat",
  "sparkles",
  "shield-heart",
  "circle-plus",
  "shuffle",
  "bomb",
  "clover",
  "mask",
  "wave",
  "bank",
  "magnet",
  "cyclone",
  "sprout",
  "beacon",
  "converge",
  "ghost",
  "repeat",
  "compass",
  "mirror",
  "stopwatch",
  "flower",
  "frame",
  "hourglass-bottom",
  "trending-up-2",
  "diamond",
  "first-aid-kit",
  "flame-heart",
  "lightning",
  "skull",
  "tornado",
  "locked",
  "fallback",
] as const;

export type PerkIconName = (typeof PERK_ICON_NAMES)[number];

export const isPerkIconName = (value: string): value is PerkIconName =>
  (PERK_ICON_NAMES as readonly string[]).includes(value);
